
ALTER SESSION SET CONTAINER = ORCLPDB1;
ALTER SESSION SET CURRENT_SCHEMA = jdbc;

BEGIN
  -- array of scalar values
  EXECUTE IMMEDIATE 'CREATE OR REPLACE TYPE test_array_type IS TABLE OF NUMBER';

END;
/
